from django.urls import path
from . import views

urlpatterns = [
    path('',views.index,name="index"),
    path('seller-index/',views.seller_index,name="seller-index"),
    path('about/',views.about,name="about"),
    path('contact/',views.contact,name="contact"),
    path('register/',views.register,name="register"),   
    path('login/',views.login,name="login"),    
    path('logout/',views.logout,name="logout"),   
    path('change-password/',views.change_password,name="change-password"),
    path('profile/',views.profile,name="profile"),
    path('forgot-password/',views.forgot_password,name="forgot-password"),
    path('verify-otp/',views.verify_otp,name="verify-otp"),
    path('new-password/',views.new_password,name="new-password"),

    path('add-product/',views.add_product,name="add-product"),
    path('delete-product/<int:pk>/',views.delete_product,name="delete-product"),
    path('edit-product/<int:pk>/',views.edit_product, name='edit-product'),
    path('seller-single-product/<int:pk>/',views.seller_single_product, name='seller-single-product'),
    path('shop/',views.shop,name="shop"),
    path('search/',views.search,name="search"),
    path('single-product/<int:pk>',views.single_product,name="single-product"),
    path('add-to-cart/<int:pk>',views.add_to_cart,name="add-to-cart"),
    path('cart/',views.cart,name="cart"),
    path('remove-from-cart/<int:pk>',views.remove_from_cart,name="remove-from-cart"),
    path('change-qty/',views.change_qty,name="change-qty"),
    path('add-to-wishlist/<int:pk>',views.add_to_wishlist,name="add-to-wishlist"),
    path('wishlist/',views.wishlist,name="wishlist"),
    path('remove-from-wishlist/<int:pk>',views.remove_from_wishlist,name="remove-from-wishlist"),
    path('create-checkout-session',views.create_checkout_session,name="payment"),
    path('success.html/',views.success,name="success"),
    path('cancel.html/',views.cancel,name="cancel"),
    path('myorder/',views.myorder,name="myorder"),
]
